- name: provisions OpenNMS
  hosts: all
  become: true
  vars:
  roles:
    - role: mrlesmithjr.ntp
    - role: mrlesmithjr.postgresql
    - role: mrlesmithjr.postfix
    - role: mrlesmithjr.oracle-java8
    - role: mrlesmithjr.opennms
  tasks:
 - name: add firewall rule
    firewalld: 
      port: 10000/tcp
      permanent: true
      state: enabled

  handlers:
    - name: reload firewall
      systemd:
        name: firewalld
        state: restarted
