- name: provisions OpenNMS
  hosts: all
  become: true
  vars:
  roles:
    - role: mrlesmithjr.ntp
    - role: mrlesmithjr.postgresql
    - role: mrlesmithjr.postfix
    - role: mrlesmithjr.oracle-java8
    - role: mrlesmithjr.opennms
  tasks:
